### ISSUE TITLE
[README] Need to add `Community Forum`

### ISSUE THREAD

**Issue by aminoxix** [layer5io/gowrk2#11]
**Description**

<a href="https://github.com/layer5io/gowrk2/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. Our community launched `Discussion forum` for help seekers; needs to publish it officially on README.md for convenience.

### Screenshots

**Current behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123441080-16209200-d5f1-11eb-8cac-0f82770161e6.png)

**Desired behaviour:**
![image](https://user-images.githubusercontent.com/75872316/123440623-9d213a80-d5f0-11eb-8ffd-87ba14c0159b.png)

**Note:**
Need to add only last line for `Community Forum`

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

---
**Reference:**
- Take reference to this <a href="https://github.com/layer5io/layer5/pull/1949">pull request</a>

**Comment by iamsdas** [comment]
I'd like to take up this issue.

**Comment by aminoxix** [comment]
@iamsdas : Cool, here you go! :rocket:

**Comment by devansh42** [comment]
Hey @iamsdas @amino19, Actually I'm wokring this issue and raised a PR https://github.com/layer5io/gowrk2/pull/12 against it. I'm new to open source development and forgot to ask for issue assignment.

**Comment by adithyaakrishna** [comment]
@devansh42 No worries, @iamsdas I hope it's okay here as he had raised the PR before. Please do look for any other open issues and tag me if you want to work on it, I will be happy to assign it to you :)

**Comment by iamsdas** [comment]
@adithyaakrishna @devansh42 sure! go ahead there are plenty of similar issues I can find.

**Comment by aminoxix** [comment]
@devansh42 : Thanks for consider, DW we're here to help you out! :slightly_smiling_face:
