### ISSUE TITLE
[Feature] - Add Issue and PR Template

### ISSUE THREAD

**Issue by adithyaakrishna** [layer5io/gowrk2#14]
**Description:** This Repo doesn't have an issue or a PR template

**Expected Behavior:** The Repository should have a Issue as well as a PR template

**For Reference:** 

- PR Template: https://github.com/layer5io/layer5/blob/master/.github/PULL_REQUEST_TEMPLATE.md
- Issue Template: https://github.com/layer5io/layer5/tree/master/.github/ISSUE_TEMPLATE
- Config File: https://github.com/layer5io/layer5/blob/master/.github/config.yml

**Comment by adithyaakrishna** [comment]
@devansh42 @amino19 Would any of you take up this issue? 👀

**Comment by aminoxix** [comment]
@adithyaakrishna : Thanks for highlighting, I will do it! :slightly_smiling_face:
