### ISSUE TITLE
Issue Template Updates for Figma link 

### ISSUE THREAD

**Issue by thisiskaransgit** [layer5io/gowrk2#19]
### Current Behavior
The project's current issue templates are missing an open invitation link where new contributors can join the community's Figma team and view user interface designs and other UX projects.

### Desired Situation
Each template that has a reference to Figma in its resources section should have an invite link added.

### Implementation 
```
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

```

**Acceptance Tests**
All references to Figma include the "open invite" link.

---
**Contributor Resources**
- See [contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by Ghat0tkach** [comment]
**This issue is for the first-timers only**.Let's get some fresh and new contributors . Here is your chance newcomers 😉

**Comment by bupd** [comment]
I am confident that I can resolve issue. I would like to be assigned to this issue.

**Comment by Ghat0tkach** [comment]
@bupd  , there you go !
