### ISSUE TITLE
Setup release drafter for the project

### ISSUE THREAD

**Issue by kushthedude** [layer5io/gowrk2#8]
**Current Situation**

Each of the layer5 repositories needs releaseDrafter automation as had been done in the meshery project which takes care of drafting release notes.

**Desired Situation**

Add ReleaseDrafter configuration yaml file & GitHub Action.

---

**Additional context**

[ReleaseDrafter Configuration File](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml)
[ReleaseDrafter GitHub Action](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml)

---
**Contributor Resources**

- See [`layer5` contributing instructions](https://github.com/layer5io/layer5/blob/master/CONTRIBUTING.md)

**Comment by leecalcote** [comment]
Additional context to the extent it helps:

**Current Situation**
The [ReleaseDrafter](https://github.com/marketplace/actions/release-drafter) utility (GitHub Action) is not configured in this repository.

**Desired Situation**
- Releasedrafter should be configured to execute whenever a PR is merged to master in this repo.

**Implementation**
- Copy the [releasedrafter config](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml) and the [releasedrafter workflow](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml) file from the `meshery` repo and place in the `.github` folder here.

**Comment by kushthedude** [comment]
Fixed in https://github.com/layer5io/gowrk2/pull/9
